config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :orders do
    member do 
      patch 'accept'
      patch 'begin'
      patch 'cancel'
      patch 'complete'
      get 'manage'
      get 'confirmation'
    end
    collection do
      get 'search'
    end
  end
  
  root 'main#home'
  
  get '/aboutus', to: 'main#aboutus'
  get '/careers', to: 'main#careers'
  get '/receiversender', to: 'main#receiversender'
  get '/receiver', to: 'main#receiver'
  get '/currierportal', to: 'main#currierportal'
  get '/new', to: 'orders#new'
  get 'confirmation', to: 'orders#confirmation'
  get '/show', to: 'orders#show'
  get '/history', to: 'orders#history'
  get '/costcalculator', to: 'orders#costcalculator'
  post 'orders/costcalculator'
  post '/orders/calculate_cost', to: 'orders#costcalculator'
  get '/currierorder', to: 'currier#currierorder'
  get '/acceptedorder', to: 'currier#acceptedorder'
  get '/routeplanner', to: 'currier#routeplanner'
  get '/curriertrack', to: 'currier#curriertrack'
  get '/currierhistory', to: 'currier#currierhistory'
  #get '/orders/search', to: 'orders#search', as: 'search_orders'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
    attr_accessor :sender_email
    belongs_to :user
    validates :user_id, presence: true
    before_validation :set_default_order_status, if: :new_record?

    enum order_status: [:Pending, :Accepted, :InProgress, :Completed, :Canceled]
    after_initialize :set_default_order_status, if: :new_record?

    def set_default_order_status
      self.order_status ||= :Pending
    end

    def costcalculator
      cost_per_item = 1.00
      cost_per_kg = 2.00
      cost_per_km = 0.10
      
      cost = (quantity * cost_per_item) + (weight * cost_per_kg) + (distance * cost_per_km)
      return cost
    end
    
end
 

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders
  validates :email, uniqueness: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :currier, :admin]
  after_initialize :set_default_role, if: :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/currier_controller.rb
class CurrierController < ApplicationController
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def home
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.order_number = SecureRandom.alphanumeric(8).upcase
    @order.sender_email = current_user.email
    if @order.save
      receiver_email = params[:order][:receiver_email]
      receiver = User.find_by(email: receiver_email)
      if receiver && receiver == current_user
        flash[:success] = "Order created!"
        redirect_to confirmation_path(@order)
      elsif receiver
        flash[:success] = "Order created!"
        redirect_to confirmation_path(id: @order.id, receiver_email: receiver_email)
      else
        flash[:warning] = "Receiver email not found"
        render :new
      end
    else
      render :new
    end
  end

  def confirmation 
    @order = Order.find(params[:id])
  end
  
  def show
    @order = current_user.orders
    if params[:from_search]
      @order = Order.find(params[:id])
    end
  end

  def search
    @order = Order.find_by(order_number: params[:order_number])
    if @order.nil?
      flash.now[:alert] = "Order not found"
    else  
      redirect_to order_path(@order)
    end
  end

  def receiver 
    receiver_email = params[:receiver_email]
    @receiver = User.find_by(email: receiver_email)
    @orders = @receiver.orders if @receiver.present?
  end

  def accept 
    @order = Order.find(params[:id])
    if current_user.currier? && @order.order_status == "Pending"
      @order.update_attribute(:order_status, "Accepted")
      @order.update_attribute(:user_id, current_user.id)
      redirect_to acceptedorder_path, notice: "Order accepted"
    else
      redirect_to currierorder_path, alert: "Unable to accept order"
    end
  end

  def manage 
    @order = Order.find(params[:id])
    render 'currier/manageorder'
  end

  def begin
    @order = Order.find(params[:id])
    if current_user.currier? && @order.order_status == "Accepted"
      @order.update_attribute(:order_status, 'InProgress')
      redirect_to acceptedorder_path, notice: 'Order is now in progress.'
    end
  end

  def cancel
    @order = Order.find(params[:id])
    @order.update_attribute(:order_status, 'Canceled')
    @order.update_attribute(:cancellation_reason, params[:cancellation_reason])
    redirect_to currierhistory_path, notice: 'Order has been canceled.'
  end

  def complete
    @order = Order.find(params[:id])
    @order.update_attribute(:order_status, 'Completed')
    redirect_to currierhistory_path, notice: 'Order has been completed.'
  end

  def history
    @completed_orders = Order.where(order_status: [:Completed, :Canceled])
  end

  def costcalculator
    weight = params[:weight].to_f
    distance = params[:distance].to_f
    quantity = params[:quantity].to_i

    cost = weight * distance * quantity * 0.05

    @cost = cost.round(2)
    render 'costcalculator'
  end
  
  
  private

  def order_params
    params.require(:order).permit(
      :sender_email,
      :order_number,
      :start_destination,
      :start_destination_address_line_1,
      :start_destination_address_line_2,
      :start_destination_city,
      :start_destination_postcode,
      :final_destination,
      :final_destination_address_line_1,
      :final_destination_address_line_2,
      :final_destination_city,
      :final_destination_postcode,
      :quantity,
      :goods_type,
      :additional_details,
      :user_id,
      :order_status,
      :cancellation_reason,
      :weight,
      :distance,
      :receiver_email,
      :pickup_datetime,
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/currier_helper.rb
module CurrierHelper
end

app/helpers/main_helper.rb
# frozen_string_literal: true

module MainHelper
end

app/helpers/manageorder_helper.rb
module ManageorderHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tracking_helper.rb
module TrackingHelper
end

app/views/currier/acceptedorder.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accepted Orders</title>
    <%= stylesheet_link_tag 'acceptedorder', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h1>Orders list</h1>
    <% Order.all.each do |order| %>
      <% if order.order_status == "Accepted" || order.order_status == "InProgress" %>
        <div class="receipt">
          <div class="order">
            <div class="header">
              <div class="order-number">Order Number: <%= order.order_number %></div>
              <div class="order-date">Order Created At: <%= order.created_at.strftime('%d %b %Y') %></div>
            </div>
            <div class="body">
              <div class="details">
                <div class="start-destination">
                  From: 
                  <%= order.start_destination_address_line_1 %>,
                  <%= order.start_destination_address_line_2 %>,
                  <%= order.start_destination_city %>,
                  <%= order.start_destination_postcode %>
                </div>
                <div class="final-destination">
                  To: 
                  <%= order.final_destination_address_line_1 %>,
                  <%= order.final_destination_address_line_2 %>,
                  <%= order.final_destination_city %>,
                  <%= order.final_destination_postcode %>
                </div>
                <div class="quantity">Quantity: <%= order.quantity %></div>
                <div class="goods-type">Goods Type: <%= order.goods_type %></div>
                <% if order.additional_details.present? %>
                  <div class="additional-details">Additional Details: <%= order.additional_details %></div>
                <% end %>
                <div class = "pickupdate">Pick-up date: <%= order.pickup_datetime %></div>
                <div class="status">
                  Status: <%= order.order_status %>
                </div>
                <div class="manage-button">
                  <%= button_to "Manage Order", manage_order_path(order.id), method: :get, class: "btn btn-primary" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="clearfix"></div>
      <% end %>
    <% end %>
  </body>
</html>

app/views/currier/currierhistory.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Order History</title>
    <%= stylesheet_link_tag 'currierhistory', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h1>Order History</h1>
    <% Order.all.each do |order| %>
      <% if order.order_status == "Canceled" || order.order_status == "Completed" %>
        <div class="receipt">
          <div class="order">
            <div class="header">
              <div class="order-number">Order Number: <%= order.order_number %></div>
              <div class="order-date">Order Date: <%= order.created_at.strftime('%d %b %Y') %></div>
            </div>
            <div class="body">
              <div class="details">
                <div class="start-destination">
                  From: 
                  <%= order.start_destination_address_line_1 %>,
                  <%= order.start_destination_address_line_2 %>,
                  <%= order.start_destination_city %>,
                  <%= order.start_destination_postcode %>
                </div>
                <div class="final-destination">
                  To: 
                  <%= order.final_destination_address_line_1 %>,
                  <%= order.final_destination_address_line_2 %>,
                  <%= order.final_destination_city %>,
                  <%= order.final_destination_postcode %>
                </div>
                <div class="quantity">Quantity: <%= order.quantity %></div>
                <div class="goods-type">Goods Type: <%= order.goods_type %></div>
                <% if order.additional_details.present? %>
                  <div class="additional-details">Additional Details: <%= order.additional_details %></div>
                <% end %>
              </div>
              <div class="status">
                Status: <%= order.order_status %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </body>
</html>

app/views/currier/currierorder.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Available Orders</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'currierorder', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h1>Available Orders</h1>
    <% Order.all.each do |order| %>
      <% if order.order_status == "Pending" %>
        <div class="receipt">
          <div class="order">
            <div class="header">
              <div class="order-number">Order Number: <%= order.order_number %></div>
              <div class="order-date">Order Date: <%= order.created_at.strftime('%d %b %Y') %></div>
            </div>
            <div class="body">
              <div class="details">
                <div class="start-destination">
                  From: 
                  <%= order.start_destination_address_line_1 %>,
                  <%= order.start_destination_address_line_2 %>,
                  <%= order.start_destination_city %>,
                  <%= order.start_destination_postcode %>
                </div>
                <div class="final-destination">
                  To: 
                  <%= order.final_destination_address_line_1 %>,
                  <%= order.final_destination_address_line_2 %>,
                  <%= order.final_destination_city %>,
                  <%= order.final_destination_postcode %>
                </div>
                <div class="quantity">Quantity: <%= order.quantity %></div>
                <div class="goods-type">Goods Type: <%= order.goods_type %></div>
                <% if order.additional_details.present? %>
                  <div class="additional-details">Additional Details: <%= order.additional_details %></div>
                <% end %>
                <div class = "pickupdate">Pick-up date: <%= order.pickup_datetime %></div>
              </div>
              <div class="status">
                Status: <%= order.order_status %>
                <% if current_user.currier? && order.order_status == "Pending" %>
                  <div class="accept">
                    <%= button_to "Accept", accept_order_path(order), method: :patch, class: "btn btn-primary" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end%>
    <% end %>
  </body>
</html>

app/views/currier/manageorder.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manage Order</title>
  <%= stylesheet_link_tag 'manageorder', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <h1>Manage Order</h1>
    <% if @order %>
      <div class="card mb-3">
        <div class="card-header">
          <h5 class="card-title">Order Number: <%= @order.order_number %></h5>
        </div>
        <div class="card-body">
          <h6 class="card-subtitle mb-2 text-muted">Destination:</h6>
          <p class="card-text">
            <%= @order.final_destination_address_line_1 %><br>
            <%= @order.final_destination_address_line_2 %><br>
            <%= @order.final_destination_city %>, <%= @order.final_destination_postcode %>
          </p>
          <h6 class="card-subtitle mb-2 text-muted">Status:</h6>
          <p class="card-text"><%= @order.order_status %></p>
          <% if current_user.currier? && @order.order_status == "Accepted" %>
            <%= button_to "Cancel", cancel_order_path(@order), method: :patch, class: "btn btn-danger" %>
            <%= button_to "Begin", begin_order_path(@order), method: :patch, class: "btn btn-primary" %>
          <% elsif current_user.currier? && @order.order_status == "InProgress" %>
            <%= button_to "Cancel", cancel_order_path(@order), method: :patch, class: "btn btn-danger" %>
            <%= button_to "Complete", complete_order_path(@order), method: :patch, class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    <% else %>
      <p class="lead">No order selected.</p>
    <% end %>
  </div>
</body>
</html>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag 'navbar', media: 'all', 'data-turbolinks-track': 'reload' %>
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">ShipIT</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/aboutus">About us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/careers">Careers</a>
        </li>
        <li class="nav-item">
          <% if current_user&.role == 'user' %>
            <a class="nav-link" href="/receiversender">Sender Portal</a>
          <% end %>
        </li>
        <li class="nav-item">
          <% if current_user&.role == 'user' %>
            <a class="nav-link" href="/receiver">Receive items</a>
          <% end %>
        </li>
        <li class="nav-item">
          <% if current_user&.role == 'currier' %>
            <a class="nav-link" href="/currierportal">Currier Portal</a>
          <% end %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/costcalculator">Cost Calculator</a>
        </li>  
      </ul>
      <ul class="navbar-nav align-items-center">
        <% if current_user %>
          <li class="nav-item"> <%= link_to "Manage my account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_newform.html.erb
<form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShipIT</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  <%= render 'layouts/navbar' %>
  <div class="container-fluid">
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/aboutus.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>About Us | ShipIT</title>
    <%= stylesheet_link_tag 'aboutus', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <h1>About us | ShipIT</h1>
      <h2>Fast, Reliable, and Affordable Delivery</h2>
      <p class="lead">We are ShipIT, a delivery company that specializes in getting your packages from point A to point B quickly and safely. Our team of expert couriers and state-of-the-art tracking technology ensure that your package arrives on time and in the same condition as when it left.</p>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <h5 class="card-title">Order Creation</h5>
            <p class="card-text">Create a new order quickly and easily with our intuitive order creation process.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <h5 class="card-title">Tracking</h5>
            <p class="card-text">Stay informed about the status of your delivery with real-time tracking updates.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <h5 class="card-title">Cost Calculator</h5>
            <p class="card-text">Get an estimate of the cost of your shipment with our easy-to-use cost calculator.</p>
          </div>
        </div>
      </div>
    </div>
  </body>
  <footer class="footer">
    <div class="container">
      <span class="text-muted">&copy; 2023 ShipIT. All Rights Reserved, Vedran Badrov.</span>
    </div>
  </footer>
</html>

app/views/main/careers.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShipIT | Careers</title>
  <%= stylesheet_link_tag 'careers', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header>
  </header>
  <main>
    <div class="container">
      <section class="job-listings">
        <h2>Job Listings</h2>
        <ul>
          <li>
            <h3>Currier</h3>
            <p>ShipIT is looking for curreirs that will help use reach goals of ShipIT and make it world recognized shipping application.</p>
            <a href="#">Apply Now</a>
          </li>
          <li>
            <h3>UI/UX Designer</h3>
            <p>ShipIT is seeking a talented UI/UX designer to help us create beautiful and intuitive interfaces for our logistics platform.</p>
            <a href="#">Apply Now</a>
          </li>
          <li>
            <h3>Customer Support Specialist</h3>
            <p>ShipIT is looking for a friendly and helpful customer support specialist to assist our clients with their shipping needs.</p>
            <a href="#">Apply Now</a>
          </li>
        </ul>
      </section>
    </div>
  </main>
  <footer class="footer">
    <div class="container">
      <span class="text-muted">&copy; 2023 ShipIT. All Rights Reserved, Vedran Badrov.</span>
    </div>
  </footer>
</body>
</html>

app/views/main/currierportal.html.erb
<h1>Currier portal</h1>

<%= stylesheet_link_tag 'currierportal', media: 'all', 'data-turbolinks-track': 'reload' %>
<script src="/receiversender.js"></script>

<div class="portal-container">
  <div class="portal-box">
    <a class="nav-link" href="/currierorder">
      <h2>Browse pending orders</h2>
      <p>Easily create a new order to send your goods from one place to another</p>
    </a>
  </div>
  <div class="portal-box">
    <a class="nav-link" href="/acceptedorder">
      <h2>My accepted orders</h2>
      <p>View and manage your currently active orders</p>
    </a>
  </div>
  <div class="portal-box">
    <a class="nav-link" href="/currierhistory">
      <h2>Currier Order History</h2>
      <p>View your past orders and their details</p>
    </a>
  </div>
</div>

app/views/main/curriersportal.html.erb
<p>Orders</p>
<p>My Orders</p>
<p>Route planner</p>
<p>Tracking</p>
<p>History of orders</p>

app/views/main/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div class="banner">
      <h1>Welcome to ShipIT</h1>
      <% if current_user %>
        <p>Hello <%= current_user.email %>, you are a <%= current_user.role %>.</p>
      <% end %>
    </div>
    <div class="container">
      <div class="main">
        <div class="content">
          <h2>Fast and Reliable Shipping Service</h2>
          <p>ShipIT offers a fast, reliable, and secure shipping service for your items.</p>
        </div>
        <div class="cta">
          <% if current_user && current_user.role == "user" %>
            <%= link_to "Ship Now", new_order_path, class: "btn btn-lg btn-ship" %>
          <% elsif current_user && current_user.role == "currier" %>
            <%= link_to "Currier Order", currierorder_path, class: "btn btn-lg btn-ship" %>
          <% else %>
            <%= link_to "Get Started", new_user_registration_path, class: "btn btn-lg btn-ship" %>
          <% end %>
        </div>
      </div>
    </div>
    <footer class="footer">
      <div class="container">
        <span class="text-muted">&copy; 2023 ShipIT. All Rights Reserved, Vedran Badrov.</span>
      </div>
    </footer>
  </body>
</html>

app/views/main/orders.html.erb
<p>Create a new orders</p>
<p>My active orders</p>
<p>Track an order</p>
<p>Order history</p>

app/views/main/receiver.html.erb
<head>
  <%= stylesheet_link_tag 'receive', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<h1>Receive Items</h1>

<% orders = Order.where(receiver_email: current_user.email) %>

<% if orders.present? %>
  <table>
    <thead>
      <tr>
        <th>Order Number</th>
        <th>Sender</th>
        <th>Quantity</th>
        <th>Goods Type</th>
        <th>Additional Details</th>
        <th>Pickup Date and Time</th>
        <th>Current order status</th>
      </tr>
    </thead>
    <tbody>
      <% orders.each do |order| %>
        <tr>
          <td><%= order.order_number %></td>
          <td><%= order.sender_email %></td>
          <td><%= order.quantity %></td>
          <td><%= order.goods_type %></td>
          <td><%= order.additional_details %></td>
          <td><%= order.pickup_datetime %></td>
          <td><%= order.order_status %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No items received for this email address.</p>
<% end %>

app/views/main/receiversender.html.erb
<!DOCTYPE html>
<html>
<head>
	<h1>Sender Portal</h1>
	<%= stylesheet_link_tag 'receiversender', media: 'all', 'data-turbolinks-track': 'reload' %>
	<script src="/receiversender.js"></script>
</head>
<body>
	<div class="portal-container">
	  <div class="portal-box">
	    <a class="nav-link" href="/new">
	      <h2>Create a new order</h2>
	      <p>Easily create a new order to send your goods from one place to another</p>
	    </a>
	  </div>
	  <div class="portal-box">
	    <a class="nav-link" href="/show">
	      <h2>My orders</h2>
	      <p>Browse any pending, accepted and in progress orders</p>
	    </a>
	  </div>
	  <div class="portal-box">
	    <a class="nav-link" href="/history">
	      <h2>Order History</h2>
	      <p>View your past orders and their details</p>
	    </a>
	  </div>
	</div>
</body>
</html>

app/views/orders/confirmation.html.erb
<h1>Order Confirmation</h1>
<%= stylesheet_link_tag 'confirmation', media: 'all', 'data-turbolinks-track': 'reload' %>
<p>Your order (Order Number: <%= @order.order_number %>) has been created successfully:</p>
<ul>
  <li>Start destination address:
    <%= @order.start_destination_address_line_1 %>,
    <%= @order.start_destination_address_line_2 %>,
    <%= @order.start_destination_city %>,
    <%= @order.start_destination_postcode %>
  </li>
  <li>Final destination address:
    <%= @order.final_destination_address_line_1 %>,
    <%= @order.final_destination_address_line_2 %>,
    <%= @order.final_destination_city %>,
    <%= @order.final_destination_postcode %>
  </li>
  <li>Quantity: <%= @order.quantity %></li>
  <li>Goods type: <%= @order.goods_type %></li>
  <% if @order.additional_details.present? %>
  <li>Additional details: <%= @order.additional_details %></li>
  <% end %>
  <li>Pick-up Date & Time: <%= @order.pickup_datetime %></li>
  <%= link_to 'View My Orders', order_path(@order), class: 'btn btn-primary' %>
</ul>

app/views/orders/costcalculator.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cost Calculator</title>
    <%= stylesheet_link_tag 'costcalculator', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="container">
      <h1>Cost Calculator</h1>
      <%= form_tag '/orders/costcalculator', method: :post do %>
        <div class="form-field">
          <%= label_tag :weight, 'Weight (in kg)' %>
          <%= number_field_tag :weight, nil, step: 0.01 %>
        </div>
        <div class="form-field">
          <%= label_tag :distance, 'Distance (in km)' %>
          <%= number_field_tag :distance, nil, step: 0.01 %>
        </div>
        <div class="form-field">
          <%= label_tag :quantity, 'Quantity' %>
          <%= number_field_tag :quantity, nil, min: 1 %>
        </div>
        <%= submit_tag 'Calculate cost' %>
      <% end %>

      <% if @cost.present? %>
        <p class="cost-info">The cost of your order is <%= number_to_currency(@cost, unit: '€') %>.</p>
      <% end %>
    </div>
  </body>
</html>

app/views/orders/track.html.erb
<h1>Track your order</h1>
<%= form_tag(search_orders_path, method: "get") do %>
  <%= label_tag(:order_number, "Enter Tracking Number:") %>
  <%= text_field_tag(:order_number) %>
  <%= submit_tag("Search") %>
<% end %>